version: "3.8"

services:
  portal-booking-app:
    build:
      context: ./portal-booking
    container_name: portal-booking-app
    networks:
      - app-network
    depends_on:
      - portal-booking-db

  portal-booking-nginx:
    image: nginx:alpine
    container_name: portal-booking-nginx

    networks:
      - app-network
  portal-booking-db:
    image: mysql:8.0.30
    container_name: portal-booking-db
    environment:
      MYSQL_ROOT_PASSWORD: ${PORTAL_BOOKING_DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${PORTAL_BOOKING_DB_DATABASE}
    ports:
      - "3307:3306"
    volumes:
      - portal-booking-db-data:/var/lib/mysql
    networks:
      - app-network

  #room service
  room-service-app:
    build:
      context: ./room-service
    container_name: room-service-app
    networks:
      - app-network
    depends_on:
      - room-service-db

  room-service-nginx:
    image: nginx:alpine
    container_name: room-service-nginx
    # ports:
    #   - "8001:80"
    networks:
      - app-network

  room-service-db:
    image: mysql:8.0.30
    container_name: room-service-db
    environment:
      MYSQL_ROOT_PASSWORD: ${ROOM_SERVICE_DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${ROOM_SERVICE_DB_DATABASE}
    volumes:
      - room-service-db-data:/var/lib/mysql
    ports:
      - "3308:3306"
    networks:
      - app-network

volumes:
  portal-booking-db-data:
  room-service-db-data:

networks:
  app-network:
    driver: bridge
